### ISSUE TITLE
Invoice form enhancement

### ISSUE THREAD

**Issue by mortoza** [mstahv/jpa-invoicer#18]
Hi Matti
Thank you so much for merging my pull requested. I see you have also improved them, thanks again.
I have requested some small modifications to the invoice form which is attached below. 

![jpa-invoicer](https://cloud.githubusercontent.com/assets/10647439/6977848/2f32d038-d994-11e4-8359-b3ff2da5d73a.png)

regards,
Mortoza

**Comment by mstahv** [comment]
Having both product and description columns suits fine and implemented in trunk. Left product column as optional, also not yet used in the default invoice template (will look at that later when making templates user configurable).

I'll not switch to use table based listing due to its usability instructions.
