### ISSUE TITLE
still getting exceptions

### ISSUE THREAD

**Issue by mortoza** [mstahv/jpa-invoicer#7]
Hi 
Thanks for your prompt reply and fixes. I have tried it but fortunately still having some issues. here is the exception:

After I run the application, I get a login window but after clicking login button, getting the following page:

**Comment by mortoza** [comment]
![image](https://cloud.githubusercontent.com/assets/10647439/6660787/4033cca0-cb77-11e4-812f-60e9ad9adb3f.png)

**Comment by mstahv** [comment]
Hi,

Looks like the app is going to OAuth (for which you need google develoeper keys for it set up). I thought I set it up so that it falls back ton "testing mode" if developer keys are not set, but apparently its is broken. I'll have to look at this at some point (before creating a series of articles based on this this demo).

**Comment by mstahv** [comment]
I guess this is now fixed.
